steps:
  - checkout: self
    persistCredentials: true
  - template: ./build.yaml
  - script: 'node common/scripts/install-run-rush.js version --bump --target-branch $(Build.SourceBranchName)'
    displayName: 'Rush Version'
  - script: 'node common/scripts/install-run-rush.js publish --apply --publish --target-branch $(Build.SourceBranchName) --set-access-level public'
    displayName: 'Rush Publish'
    condition: and(succeeded(), eq(variables['Build.SourceBranchName'], 'master'))
    env:
      NPM_AUTH_TOKEN: $(npmToken)
